<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-NQRRDTM" name="tests.ride.api.Marti_Operator_App_API" tests="1" failures="1" timestamp="15 Eyl 2020 14:25:18 GMT" time="4.567" errors="0">
  <testcase name="TC_028_swapper_batteryDetail" time="4.567" classname="tests.ride.api.Marti_Operator_App_API">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [BATTERY_NOT_FOUND]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [BATTERY_NOT_FOUND]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at utilities.TestBase.run_ws(TestBase.java:310)
at tests.ride.api.Marti_Operator_App_API.TC_028_swapper_batteryDetail(Marti_Operator_App_API.java:652)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_028_swapper_batteryDetail -->
</testsuite> <!-- tests.ride.api.Marti_Operator_App_API -->
